location @txvalidator {
    proxy_set_header HOST g2-validator-transaction.pnp3.pcf.dell.com;
    proxy_pass https://txvalidator_pcf;
    health_check uri=https://g2-validator-transaction.pnp3.pcf.dell.com/health interval=5 passes=3 fails=3;
}