include /etc/nginx/conf.d/txvalidator/txvalidator_upstreams.conf;

server {

  listen 80;
  status_zone g2-validator-transaction.cpps-np.us.dell.com_80;
  server_name g2-validator-transaction.cpps-np.us.dell.com;		
  merge_slashes on;
  access_log /var/log/nginx/txvalidator-access.log timed_combined;

  location / {
    return 308 https://$host$request_uri;
  }
}

server {

  listen 443 ssl;
  status_zone g2-validator-transaction.cpps-np.us.dell.com_443;
  server_name g2-validator-transaction.cpps-np.us.dell.com;		
  merge_slashes on;

## cert key

  ssl_certificate /etc/nginx/dellcert/txvalidatorCert.pem;
  ssl_certificate_key /etc/nginx/dellcert/txvalidatorKey.pem;

  access_log /var/log/nginx/txvalidator-access.log timed_combined;

   location / {
    proxy_set_header Connection "";
    proxy_set_header HOST g2-validator-transaction.pnp3.pcf.dell.com;
    proxy_pass_header Server;
    proxy_pass https://txvalidator_pcf;
  }

include /etc/nginx/conf.d/txvalidator/txvalidator_healthcheck.conf;

}
				