include /etc/nginx/conf.d/txvalidator/txvalidator_upstream.conf;

server {
  listen 80;
  status_zone product-validator-transaction.cpps.us.dell.com_80;
  server_name product-validator-transaction.cpps.us.dell.com;
  merge_slashes on;
  access_log /var/log/nginx/txvalidator-access.log timed_combined;

  location / {
    return 308 https://$host$request_uri;
  }
}

server {

  listen 443 ssl;
  status_zone product-validator-transaction.cpps.us.dell.com_443;
  server_name product-validator-transaction.cpps.us.dell.com;
  merge_slashes on;

##  cert and key

  ssl_certificate /etc/nginx/dellcert/txvalidatorCert.pem;
  ssl_certificate_key /etc/nginx/dellcert/txvalidatorKey.pem;

  access_log /var/log/nginx/txvalidator-access.log timed_combined;

  location / {
      error_page 502 = @err;
      proxy_set_header Connection "";
      proxy_set_header HOST product-validator-transaction.g8p.pcf.dell.com;
      proxy_pass_header Server;
      proxy_pass https://txvalidator_pcf;
  }
  
   location @err {
        proxy_set_header Connection "";
        proxy_pass_header Server;
        proxy_set_header HOST product-validator-transaction.g8p.pcf.dell.com;
        proxy_pass https://txvalidator_pcf_fallback;
    }

  include /etc/nginx/conf.d/txvalidator/txvalidator_healthcheck.conf;
}
